/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,vue}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: {
          50: 'var(--ui-colors-primary-50)',
          100: 'var(--ui-colors-primary-100)',
          200: 'var(--ui-colors-primary-200)',
          300: 'var(--ui-colors-primary-300)',
          400: 'var(--ui-colors-primary-400)',
          500: 'var(--ui-colors-primary-500)',
          600: 'var(--ui-colors-primary-600)',
          700: 'var(--ui-colors-primary-700)',
          800: 'var(--ui-colors-primary-800)',
          900: 'var(--ui-colors-primary-900)',
          DEFAULT: 'var(--ui-colors-primary-500)',
          light: 'var(--ui-colors-primary-400)',
          dark: 'var(--ui-colors-primary-600)',
        },
        success: 'var(--ui-colors-success)',
        warning: 'var(--ui-colors-warning)',
        error: 'var(--ui-colors-error)',
        recording: 'var(--ui-colors-recording)',
        playback: 'var(--ui-colors-playback)',
        info: 'var(--ui-colors-info)',
        gray: {
          50: 'var(--ui-colors-gray-50)',
          100: 'var(--ui-colors-gray-100)',
          200: 'var(--ui-colors-gray-200)',
          300: 'var(--ui-colors-gray-300)',
          400: 'var(--ui-colors-gray-400)',
          500: 'var(--ui-colors-gray-500)',
          600: 'var(--ui-colors-gray-600)',
          700: 'var(--ui-colors-gray-700)',
          800: 'var(--ui-colors-gray-800)',
          900: 'var(--ui-colors-gray-900)',
        },
      },
      fontSize: {
        'xs': 'var(--ui-font-size-xs)',
        'sm': 'var(--ui-font-size-sm)',
        'base': 'var(--ui-font-size-base)',
        'lg': 'var(--ui-font-size-lg)',
        'xl': 'var(--ui-font-size-xl)',
        '2xl': 'var(--ui-font-size-2xl)',
        '3xl': 'var(--ui-font-size-3xl)',
        '4xl': 'var(--ui-font-size-4xl)',
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '7': '1.75rem',
        '8': '2rem',
        '9': '2.25rem',
        '10': '2.5rem',
        '11': '2.75rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
      },
      borderRadius: {
        'sm': 'var(--ui-radius-sm)',
        'md': 'var(--ui-radius-md)',
        'lg': 'var(--ui-radius-lg)',
        'xl': 'var(--ui-radius-xl)',
        '2xl': 'var(--ui-radius-2xl)',
        '3xl': 'var(--ui-radius-3xl)',
        'full': 'var(--ui-radius-full)',
      },
      boxShadow: {
        'sm': 'var(--ui-shadows-sm)',
        'md': 'var(--ui-shadows-md)',
        'lg': 'var(--ui-shadows-lg)',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
    },
  },
  plugins: [],
};
